(() => {
  const types = ["HERO_CAMPAIGN", "FULL_WIDTH_BANNER", "SPLIT_STORY", "EDITORIAL_STORY", "BRAND_STORY", "PROMOTIONAL_STRIP"];
  const imageLimit = 2 * 1024 * 1024;
  const previewStyle = document.createElement("style");
  previewStyle.textContent = ".studio-image-preview{display:flex;gap:8px;margin-top:4px}.studio-image-preview img{width:72px;height:48px;object-fit:cover;border:1px solid #d7dfeb;border-radius:6px}";
  document.head.appendChild(previewStyle);
  const field = (name, label, type = "text") => `<label class="field">${label}<input name="${name}" type="${type}"></label>`;
  const imageField = (name, label) => `<label class="field">${label}<input name="${name}" placeholder="Optional image URL"><input id="${name}File" type="file" accept="image/jpeg,image/png,image/webp"><small>Or choose a local image file (max 2 MB)</small><div class="studio-image-preview" id="${name}Preview"></div></label>`;
  const studioMarkup = `<section class="panel" id="studioPanel"><div class="panel-head"><div><span class="eyebrow">Homepage content studio</span><h2>Shape the live homepage</h2></div><span id="studioState">Session protected</span></div><form class="form" id="studioForm"><input name="id" type="hidden"><label class="field">Section type<select name="type">${types.map((type) => `<option value="${type}">${type.replaceAll("_", " ")}</option>`).join("")}</select></label>${field("displayOrder", "Display order", "number")}${field("title", "Title")}${field("subtitle", "Subtitle")}<label class="field full">Description<textarea name="description" rows="2"></textarea></label>${imageField("image", "Desktop image")}${imageField("mobileImage", "Mobile image")}${field("ctaLabel", "CTA label")}${field("ctaUrl", "CTA destination")}<label class="checks full"><label><input name="active" type="checkbox" checked> Active on homepage</label></label><button class="primary" type="submit">Save homepage section</button></form><div id="studioList" class="queue"></div></section>`;
  const api = async (path, options = {}) => { const response = await fetch(`/api/admin${path}`, { credentials: "same-origin", ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Content update failed."); return data; };
  const form = () => document.querySelector("#studioForm");
  const fileAsDataUrl = (file) => new Promise((resolve, reject) => { if (!file) return resolve(""); if (file.size > imageLimit) return reject(new Error("Each homepage image must be 2 MB or smaller.")); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error("Could not read homepage image.")); reader.readAsDataURL(file); });
  const previewFile = (input, preview) => { const file = input.files[0]; preview.innerHTML = file ? `<img src="${URL.createObjectURL(file)}" alt="Selected image preview">` : ""; };
  const resetForm = () => { form().reset(); form().id.value = ""; form().active.checked = true; form().querySelector("button[type=submit]").textContent = "Save homepage section"; document.querySelectorAll(".studio-image-preview").forEach((preview) => { preview.innerHTML = ""; }); };
  const edit = (section) => { const target = form(); Object.entries(section).forEach(([key, value]) => { if (target.elements[key] && typeof value !== "object") target.elements[key].value = value ?? ""; }); target.id.value = section._id; target.active.checked = section.active; ["image", "mobileImage"].forEach((key) => { const preview = document.querySelector(`#${key}Preview`); preview.innerHTML = section[key] ? `<img src="${section[key]}" alt="Current image preview">` : ""; }); target.querySelector("button[type=submit]").textContent = "Update homepage section"; target.scrollIntoView({ behavior: "smooth", block: "center" }); };
  const render = (sections) => { const list = document.querySelector("#studioList"); if (!list) return; list.innerHTML = sections.length ? sections.map((section, index) => `<div class="order"><strong>${section.displayOrder}. ${section.title || section.type}</strong><small>${section.type} · ${section.active ? "Visible" : "Hidden"}<br>${section.description || "No description"}</small><button class="ghost" data-edit-section="${section._id}">Edit</button><button class="ghost" data-move-section="${section._id}" data-direction="up" ${index === 0 ? "disabled" : ""}>Move up</button><button class="ghost" data-move-section="${section._id}" data-direction="down" ${index === sections.length - 1 ? "disabled" : ""}>Move down</button><button class="danger" data-remove-section="${section._id}">Remove</button></div>`).join("") : '<p class="notice">No homepage sections yet. Add the first campaign above.</p>'; list.querySelectorAll("[data-edit-section]").forEach((button) => { button.onclick = () => edit(sections.find((section) => section._id === button.dataset.editSection)); }); list.querySelectorAll("[data-remove-section]").forEach((button) => { button.onclick = async () => { await api(`/content/sections/${button.dataset.removeSection}`, { method: "DELETE" }); load(); }; }); list.querySelectorAll("[data-move-section]").forEach((button) => { button.onclick = async () => { const currentIndex = sections.findIndex((section) => section._id === button.dataset.moveSection); const nextIndex = button.dataset.direction === "up" ? currentIndex - 1 : currentIndex + 1; if (nextIndex < 0 || nextIndex >= sections.length) return; const current = sections[currentIndex]; const next = sections[nextIndex]; await Promise.all([api(`/content/sections/${current._id}`, { method: "PUT", body: JSON.stringify({ ...current, displayOrder: next.displayOrder }) }), api(`/content/sections/${next._id}`, { method: "PUT", body: JSON.stringify({ ...next, displayOrder: current.displayOrder }) })]); load(); }; }); };
  async function load() { try { const data = await api("/content"); render(data.sections || []); } catch (error) { const status = document.querySelector("#studioState"); if (status) status.textContent = error.message; } }
  function mount() { if (document.querySelector("#studioPanel")) return; const shell = document.querySelector("#shell"); if (!shell || !shell.classList.contains("open")) return; shell.insertAdjacentHTML("beforeend", studioMarkup); ["image", "mobileImage"].forEach((key) => { const input = document.querySelector(`#${key}File`); input.onchange = () => previewFile(input, document.querySelector(`#${key}Preview`)); }); form().onsubmit = async (event) => { event.preventDefault(); const target = event.target; const values = Object.fromEntries(new FormData(target)); const id = values.id; delete values.id; try { const desktopFile = await fileAsDataUrl(document.querySelector("#imageFile").files[0]); const mobileFile = await fileAsDataUrl(document.querySelector("#mobileImageFile").files[0]); await api(id ? `/content/sections/${id}` : "/content/sections", { method: id ? "PUT" : "POST", body: JSON.stringify({ ...values, image: desktopFile || values.image, mobileImage: mobileFile || values.mobileImage, displayOrder: Number(values.displayOrder || 0), active: target.active.checked }) }); resetForm(); load(); } catch (error) { document.querySelector("#studioState").textContent = error.message; } }; load(); }
  const observer = new MutationObserver(mount); observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["class"] }); window.setTimeout(mount, 500);
})();
